<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>alpha.4</VersionSuffix>
    <Company>AstralTFT</Company>
    <Product>AstralTFT</Product>
  </PropertyGroup>
</Project>
